# Generated by Django 3.0.5 on 2020-04-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrol_datetime',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_booking',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='organization',
            field=models.CharField(max_length=100),
        ),
    ]
